# Generated by Django 4.2.3 on 2023-07-20 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pte1', models.PositiveBigIntegerField(default=0)),
                ('pte2', models.PositiveBigIntegerField(default=0)),
                ('potencia', models.FloatField(default=3.14)),
                ('chassis', models.CharField(max_length=50)),
                ('slots', models.PositiveIntegerField(default=1)),
                ('ports', models.PositiveIntegerField(default=1)),
                ('created_device', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('fila', models.CharField(max_length=50)),
                ('bastidor', models.CharField(max_length=50)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datacenter.device')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datacenter.location')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datacenter.location'),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datacenter.type'),
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontaA', models.CharField(max_length=50)),
                ('pontaB', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('updated_cable', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('deviceA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_A', to='datacenter.device')),
                ('deviceB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_B', to='datacenter.device')),
            ],
        ),
    ]
